name: Enhancement
description: Suggest a new feature.
labels: ["enhancement", "pending triage"]
title: "[ENHANCEMENT] - "
body:
  - type: checkboxes
    attributes:
      label: Issue Checklist
      options:
        - label: Have you got the issue title right?
        - label: Have you checked the Issues/Discussions to see if this hasn't been previously suggested yet?

  - type: textarea
    attributes:
      label: What is your suggestion, and why should it be implemented?
