name: "Issue Labeler"
on:
  issues:
    types:
      - opened
      - reopened
      - edited

jobs:
  # When an issue is opened, perform a similarity check for potential duplicates.
  # If some are found, add a label and comment listing the potential duplicate issues.
  potential-duplicate:
    name: Detect potential duplicate issues
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/potential-duplicates@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Issue title filter work with anymatch https://www.npmjs.com/package/anymatch.
          # Any matched issue will stop detection immediately.
          # You can specify multi filters in each line.
          filter: ''
          # Exclude keywords in title before detecting.
          exclude: ''
          # Label to set, when potential duplicates are detected.
          label: 'potential duplicate'
          # Get issues with state to compare. Supported state: 'all', 'closed', 'open'.
          state: all
          # If similarity is higher than this threshold([0,1]), issue will be marked as duplicate.
          # Turn this up if the detection is too sensitive
          threshold: 0.6
          # Reactions to be add to comment when potential duplicates are detected.
          # Available reactions: "-1", "+1", "confused", "laugh", "heart", "hooray", "rocket", "eyes"
          # reactions: '-1'
          # Comment to post when potential duplicates are detected.
          comment: >
            potential dupes: {{#issues}}
              - [#{{ number }}] {{ title }} ({{ accuracy }}%)
            {{/issues}}

            please note that this detection may not be fully accurate so it might be mistaking this unrelated issue with another!!
  # When an issue is opened, detect if it has an empty body or incomplete issue form.
  # If it does, close the issue immediately.
  empty-issues:
    name: Close empty issues
    runs-on: ubuntu-latest
    steps:
    - name: Run empty issues closer action
      uses: rickstaa/empty-issues-closer-action@v1
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      with:
        close_comment: gonna  close this issue cuz the issue info is incomplete! pls update the issue for it to be reopened
        open_comment: finally you gave more info about the issue, finna reopen it